// Supplemental interface copy. Learning texts and target-language dialogue stay in their source language.
// Keys use trimmed JSX text; English fragments retain spaces needed around interpolated values.
export const extraEnglish: Record<string, string> = {
  "内容草稿": "Draft",
  "已复核": "Reviewed",
  "已发布": "Published",
  "已归档": "Archived",
  "进度同步失败": "Progress sync failed",
  "词汇统计同步失败": "Vocabulary statistics sync failed",
  "收藏同步失败": "Bookmark sync failed",
  "语言偏好同步失败": "Language preference sync failed",
  "交流社区": "Community",
  "个人设置": "Settings",
  "哔丘 Pikku": "Pikku",
  "查看源代码": "View source repository",
  "源代码": "Source",
  "账户记录同步中…": "Syncing account records…",
  "记录同步失败，请保持登录并重试": "Sync failed. Stay signed in and retry.",
  "有序选题": "Ordered practice",
  "剧情任务": "Story tasks",
  "随机组卷": "Random paper",
  "背单词": "Vocabulary trainer",
  "词汇量测量": "Vocabulary check",
  "错题回炉": "Review mistakes",
  "我的收藏": "Bookmarks",
  "考试范围": "Exam scope",
  "真题档案": "Past-paper archive",
  "教材·作者·辞典": "Textbooks · Authors · Dictionaries",
  "考试与资源": "Exams & resources",
  "语言学习首页": "Language home",
  "训练中心": "Practice center",
  "复习中心": "Review center",
  "考试模拟": "Mock exam",
  "自适应背单词": "Adaptive vocabulary",
  "考试档案": "Exam archive",
  "教材与辞典": "Textbooks & dictionaries",
  "管理员后台": "Admin panel",
  "学习中心": "Learning center",
  "已接入共享训练闭环；当前等级为": " uses the shared practice and review flow. Current level: ",
  "，已有": "; available: ",
  "道种子题。": " seed questions.",
  "语言选择": "Language selection",
  "已完成": "Complete",
  "等级映射": "Level mapping",
  "首批题库": "Initial question bank",
  "题": " questions",
  "训练与复习": "Practice & review",
  "有序、随机、错题和收藏复用同一稳定交互，题目按语言隔离。": "Ordered practice, random practice, mistakes and bookmarks share the same controls, with separate question banks for each language.",
  "开始": "Start ",
  "练习": " practice",
  "自适应背词": "Adaptive vocabulary",
  "根据本账号的记得／忘了记录持续调整出词，当前等级可无限连续训练。": "Words adapt to this account’s remembered and forgotten responses. Continue practicing at your current level without a daily limit.",
  "背词": " vocabulary",
  "资源与社区": "Resources & community",
  "教材、辞典和目标语言频道保留独立入口，审核能力完成后再开放发帖。": "Textbooks, dictionaries and target-language channels have separate entries. Posting will open when moderation is ready.",
  "打开": "Open ",
  "资源": " resources",
  "PIKKU LANGUAGES · 随机语言知识": "PIKKU LANGUAGES · LANGUAGE NOTE",
  "例子": "Example",
  "来源": "Source",
  "换一条": "Another",
  "公开版 · 本机记录": "Public version · Local records",
  "登录 / 注册": "Sign in / Register",
  "管理员": "Administrator",
  "学习账号": "Learner account",
  "退出后可切换 ChatGPT 账号": "Sign out to switch ChatGPT accounts",
  "退出 / 换号": "Sign out / Switch",
  "请填写姓名、有效邮箱和至少 10 位密码。": "Enter your name, a valid email address and a password of at least 10 characters.",
  "请输入邮箱和至少 10 位密码。": "Enter your email address and a password of at least 10 characters.",
  "注册成功。请打开验证邮件完成确认，然后返回登录。测试邮件每小时有发送上限。": "Registration successful. Confirm your email, then return to sign in. Verification emails have an hourly sending limit.",
  "GitHub 管理员": "GitHub administrator",
  "退出前会等待当前进度同步完成": "Current progress will finish syncing before sign-out",
  "同步中…": "Syncing…",
  "关闭登录窗口": "Close sign-in dialog",
  "Ratio studiorum · 学习账户": "Ratio studiorum · LEARNER ACCOUNT",
  "登录比丘拟": "Sign in to Pikku",
  "创建学习账号": "Create a learner account",
  "学习者使用邮箱账号；GitHub 入口仅供已列入白名单的开发者和管理员。": "Learners sign in with email. GitHub sign-in is reserved for approved developers and administrators.",
  "登录": "Sign in",
  "注册": "Register",
  "显示姓名": "Display name",
  "邮箱": "Email",
  "密码": "Password",
  "处理中…": "Working…",
  "登录并同步进度": "Sign in and sync progress",
  "注册账号": "Create account",
  "其他登录方式": "Other sign-in methods",
  "打开微信二维码完成登录": "Open the WeChat QR code to sign in",
  "配置正式域名和微信开放平台后启用": "Available after the production domain and WeChat Open Platform are configured",
  "使用微信扫码登录": "Sign in with WeChat QR code",
  "微信扫码登录 · 配置中": "WeChat QR sign-in · Setup in progress",
  "开发者 / 管理员": "Developers / Administrators",
  "使用 GitHub 登录": "Sign in with GitHub",
  "FABULA INVESTIGANDA · P3.3 原型": "FABULA INVESTIGANDA · P3.3 PROTOTYPE",
  "香山碑文与版本线索": "The Xiangshan Inscription and Textual Clues",
  "和“五方言路”完成一条 8–12 分钟的拉丁语文献侦探任务；另有 3 分钟复习和 20 分钟深读。": "Join the Five Dialect Roads cast for an 8–12 minute Latin text-detective task, with a 3-minute review and a 20-minute close-reading route.",
  "进入剧情": "Enter story",
  "FABULA INVESTIGANDA · 剧情任务": "FABULA INVESTIGANDA · STORY TASK",
  "建议中级 · 所有等级可试": "Intermediate recommended · Open to all levels",
  "。你会先理解线索、向同伴缩小问题、提交转写判断，再把同一策略迁移到新句。": ". Interpret the clues, narrow down the question with a partner, choose a transcription, then apply the same strategy to a new sentence.",
  "原创训练场景 · 非史料原文 · 不设性别、国籍或身份预设": "Original learning scenario · Not a historical source text · No assumed gender, nationality or identity",
  "剧情任务设置": "Story task settings",
  "TEMPO · 任务长度": "TEMPO · TASK LENGTH",
  "这次走哪条路线？": "Which route will you take?",
  "引导强度": "Guidance level",
  "只影响提示多少，不改变题目结果。": "Changes the amount of guidance, not how answers are scored.",
  "更多讲解": "More guidance",
  "更沉浸": "More immersive",
  "返回训练中心": "Back to practice",
  "ECHO COMPLETUM · 闭环完成": "ECHO COMPLETUM · LEARNING CYCLE COMPLETE",
  "线索已经串起来了。": "The clues now fit together.",
  "本轮完成": "This session covered ",
  "个情境节点，": " scene steps. Across ",
  "次判断中命中": " decisions, you answered ",
  "次。错选不会阻断剧情；反馈已把注意力带回有限动词、名词与分词的一致关系。": " correctly. Wrong answers do not block the story; feedback points you back to finite verbs and noun–participle agreement.",
  "核心策略": "Core strategy",
  "先主干，后分词一致": "Find the main clause, then check participle agreement",
  "目标词目": "Target words",
  "本轮路线": "Session route",
  "3 分钟回声复习": "3-minute recall review",
  "打开 20 分钟深读": "Open 20-minute close reading",
  "打开资源库": "Open resources",
  "回到训练中心": "Back to practice",
  "本阶段为静态原型，只在本次章节中计算判断结果；账号级剧情进度和错因权重将在下一迭代接入。": "This prototype scores only the current chapter. Account-level story progress and mistake weighting are planned for a later iteration.",
  "退出任务": "Exit task",
  "学习闭环阶段": "Learning cycle stages",
  "观察提示": "Observation hint",
  "文献深读注": "Close-reading note",
  "线索成立": "Clue confirmed",
  "先保留这个误差": "Let’s examine this mismatch",
  "修复提示：": "Correction hint: ",
  "上一幕": "Previous scene",
  "返回设置": "Back to settings",
  "完成任务": "Complete task",
  "继续": "Continue",
  "难度": "Difficulty",
  "模块": "Module",
  "全部模块": "All modules",
  "顺序": "Order",
  "教材域有序": "Textbook order",
  "随机洗牌": "Shuffle",
  "搜索题号、题干、标签、作者或来源（如 Livy）": "Search ID, prompt, tag, author or source (e.g. Livy)",
  "原创复核题": "Original review question",
  "公版原文": "Public-domain text",
  "官方框架": "Official framework",
  "取消收藏": "Remove bookmark",
  "收藏题目": "Bookmark question",
  "选择答案": "Choose an answer",
  "提交答案": "Submit answer",
  "你的分析": "Your analysis",
  "你的译文": "Your translation",
  "写出词典形、时态、语气、人称数、语态意义和分词一致……": "Identify the dictionary form, tense, mood, person, number, voice meaning and participle agreement…",
  "先找谓语和主句骨架，再逐层处理从句……": "Find the finite verb and main-clause frame, then work through each subordinate clause…",
  "对照参考分析": "Compare with model analysis",
  "对照参考译文": "Compare with model translation",
  "参考分析": "Model analysis",
  "参考译文": "Model translation",
  "这句掌握了吗？": "How well do you know this sentence?",
  "基本掌握": "Mostly mastered",
  "需要复习": "Needs review",
  "错因对照": "Compare mistake explanations",
  "Recte! 回答正确": "Recte! Correct",
  "再看一次形态线索": "Check the morphological clues again",
  "本级词库正在整理": "Vocabulary for this level is being prepared",
  "切换等级后再试，或稍后等待词卡扩充。": "Try another level or return when more cards are available.",
  "PIKKU ADAPTĪVUM · 连续训练": "PIKKU ADAPTĪVUM · CONTINUOUS PRACTICE",
  "当前涵盖": "Vocabulary: ",
  "词库。没有每日上限；没记住的词会提高权重，熟词仍会低频复现，最近出现的词会暂时降权。": ". There is no daily limit. Forgotten words appear more often; familiar words return less often, and recently seen words temporarily receive less weight.",
  "显示设置": "Display settings",
  "背词统计": "Vocabulary statistics",
  "本轮": "This session",
  "次判断": "responses",
  "本轮记得": "Remembered this session",
  "尚未作答": "No responses yet",
  "范围历史": "History for this range",
  "单词＋语境": "Word + context",
  "纯单词": "Word only",
  "释义": "Meaning",
  "显示释义": "Show meaning",
  "记忆反馈": "Recall feedback",
  "忘了": "Forgotten",
  "提高后续出现权重": "Show more often",
  "记得": "Remembered",
  "降低但不永久移除": "Show less often, but keep reviewing",
  "Pikku 依据本账号累计的见词次数与记得次数计算透明权重；首版不声称复现任何第三方未公开算法。": "Pikku weights words using this account’s cumulative views and remembered responses. This version does not claim to reproduce any third party’s unpublished algorithm.",
  "设置适用于拉丁语、日语和西班牙语背词训练；切换语言时无需重复调整。": "These settings apply to Latin, Japanese and Spanish vocabulary practice. You do not need to adjust them again when switching languages.",
  "背单词显示模式": "Vocabulary display mode",
  "当前设置会随学习账号同步。": "Your settings sync with your learner account.",
  "当前为游客状态，设置和记忆记录保存在本机；登录后可写入账号。": "You are browsing as a guest. Settings and recall records stay on this device and can be added to your account after sign-in.",
  "纯单词记忆": "Word-only recall",
  "只显示词目，减少提示干扰。": "Show only the word, with fewer contextual hints.",
  "纯单词＋语境": "Word + context",
  "词目下方用小字显示一条短例句。": "Show a short example sentence beneath the word.",
  "当前语言：": "Current language: ",
  "开始背单词": "Start vocabulary practice",
  "已保存并立即写入题库覆盖层。": "Saved and applied to the question-bank override layer.",
  "保存失败": "Save failed",
  "题目已停用。": "Question disabled.",
  "停用失败": "Disable failed",
  "栏目分页": "Section tabs",
  "教材、作者与辞典": " textbooks, authors & dictionaries",
  "当前页面只显示": "Showing only ",
  "资源；切换学习语言后，教材、作者、词条和语言知识会同步切换。": " resources. Textbooks, authors, dictionary entries and language notes change with your learning language.",
  "教材对齐": "Textbook alignment",
  "作者图谱": "Author map",
  "语言知识": "Language notes",
  "版权与改编原则": "Copyright & adaptation",
  "只索引官方页面、公版文献和合法预览。版权教材用于知识点与考纲映射，公开题库发布原创题目，不上传来源不明的 PDF，也不复刻整章练习。": "We index official pages, public-domain texts and lawful previews. Copyrighted textbooks inform topic and syllabus mapping; public questions are original. We do not upload PDFs of uncertain origin or reproduce entire exercise chapters.",
  "难度域映射": "Level alignment",
  "初级": "Elementary",
  "中级": "Intermediate",
  "混合": "Mixed",
  "从初级与中级任务按能力域抽取，不另造教材进度。": "Draws from elementary and intermediate tasks by skill area, without creating a separate textbook sequence.",
  "进阶": "Advanced",
  "教材待建": " textbooks are being prepared",
  "当前模式不会借用拉丁语教材；核验书目与课程映射后再加入。": "Textbooks for this language will be added after the bibliography and course alignment are verified.",
  "章节与原创练习映射": "Chapter-to-exercise mapping",
  "只含元数据，不包含教材正文、答案或音频": "Metadata only; no textbook text, answers or audio",
  "语法域": "Grammar targets",
  "词汇域": "Vocabulary targets",
  "原创化逻辑": "Original exercise design",
  "尚无章节映射": "No chapter mappings yet",
  "章节元数据仍在核验，不显示其他语言的占位内容。": " chapter metadata is still being verified. Content from other languages is not used as a placeholder.",
  "位首批作者": "featured authors",
  "条作者—作品关系": "author–work links",
  "个历史分期": "historical periods",
  "建议域：": "Suggested level: ",
  "作者图谱待建": " author map is being prepared",
  "当前模式不会借用拉丁语作者数据；按语言与时代核验后再加入。": "Authors for this language will be added after their language and historical period are verified.",
  "当前筛选／": "Filtered / ",
  "词条": " entries",
  "最近一批新增": "Added in the latest batch",
  "已建词条": " entries available",
  "批次": "Batch",
  "全部批次": "All batches",
  "基础词库": "Core lexicon",
  "内容状态": "Review status",
  "全部状态": "All statuses",
  "词条核验规则": "Entry verification",
  "每周复盘先收录本周实际接触但尚未入库的词汇，再逐条核对词典形、语义、词源与例句；下列五种拉丁语辞典分别记录核验状态。": "Weekly reviews add newly encountered words, then check their headwords, meanings, etymologies and examples. Verification is tracked separately for each of the five Latin dictionaries below.",
  "搜索词头、读音、中文义或派生词": "Search headword, pronunciation, Chinese meaning or derivative",
  "词源线索": "Etymological clues",
  "派生／用法提示": "Derivatives & usage",
  "待补充": "Not yet available",
  "批次 ·": "Batch · ",
  "专项词典 · 待核": "Specialist dictionary · Pending verification",
  "周复盘新增 ·": "Added in weekly review · ",
  "没有匹配词条": "No matching entries",
  "换一个关键词、批次或内容状态；当前页面只查询": "Try another keyword, batch or review status. Searching only the ",
  "词库。": " lexicon.",
  "现有词源知识已接入首页随机栏目；后续按拉丁词、后裔词、语义变化与来源逐条扩充。": "Existing etymology notes also appear on the home page. Future entries will add Latin words, descendants, semantic changes and sources.",
  "英语：": "English: ",
  "罗曼语：": "Romance languages: ",
  "语言知识待建": " language notes are being prepared",
  "核验来源后再加入，不显示拉丁语占位内容。": "Notes for this language will be added after their sources are verified.",
  "公共拉丁语频道": "Public Latin channel",
  "正文只使用拉丁语。可交流日常、阅读原典、主动拉丁语写作与翻译；引用其他语言时需附拉丁语说明。": "Write posts in Latin. Discuss everyday life, original texts, active Latin writing and translation. Quotations in other languages need a Latin explanation.",
  "日语限定频道": "Japanese-only channel",
  "正文只使用日语。可交流日常、阅读、写作和翻译；引用其他语言时需附日语说明。": "Write posts in Japanese. Discuss everyday life, reading, writing and translation. Quotations in other languages need a Japanese explanation.",
  "西班牙语限定频道": "Spanish-only channel",
  "正文只使用西班牙语。可交流日常、阅读、写作和翻译；引用其他语言时需附西班牙语说明。": "Write posts in Spanish. Discuss everyday life, reading, writing and translation. Quotations in other languages need a Spanish explanation.",
  "在这里分享学习方法与目标语言练习。": "Share learning methods and target-language practice here.",
  "频道结构已预留；账号、举报、限流与审核规则完成后再开放发帖。": "Channels are planned. Posting will open when accounts, reporting, rate limits and moderation are ready.",
  "即将开放": "Coming soon",
  "网站与学习频道": "Site & study channel",
  "可使用界面语言，只讨论网站设计、功能优化、报错、学习方法和使用心得。": "Use your interface language to discuss site design, feature improvements, bug reports, learning methods and experiences.",
  "为什么暂不直接开放？": "Why is posting not open yet?",
  "公共社区需要先具备内容举报、管理员审核、频率限制、隐私说明和数据保留规则，避免测试功能变成安全缺口。": "A public community needs reporting, moderation, rate limits, privacy information and data-retention rules before posting opens.",
  "设置适用于所有学习语言的背词训练；切换语言时无需重复调整。": "These vocabulary settings apply to all learning languages and stay the same when you switch.",
  "剧情进度": "Story progress",
  "暂无内容": "Nothing here yet",
  "词典": "Dictionary",
  "频道": "Channel",
  "新词卡": "new word cards",
  "进入情境": "Enter the scene",
  "探索线索": "Explore clues",
  "协商意义": "Negotiate meaning",
  "作出判断": "Make a decision",
  "注意形式": "Notice form",
  "延迟提取": "Recall later",
  "快速复习": "Quick review",
  "约 3 分钟": "About 3 minutes",
  "保留核心判断与回声提取。": "Practice the key decisions and later recall.",
  "主线任务": "Main story",
  "8–12 分钟": "8\u201312 minutes",
  "完成六阶段自然习得闭环。": "Complete the six-stage learning cycle.",
  "文献深读": "Close reading",
  "约 20 分钟": "About 20 minutes",
  "加入词形、碑铭转写与版本说明。": "Add morphology, inscription transcription and edition notes.",
};
