const zh = {
  home: '学习台', practice: '练习', words: '背词', account: '我的', resources: '资源',
  title: '每天学一点，世界近一点。', subtitle: '同一个 Pikku，随时继续你的语言之旅。',
  learning: '学习语言', display: '显示语言', start: '开始练习', all: '全部题目', wrong: '错题复习', saved: '我的收藏',
  answered: '已完成', correct: '答对', bookmarked: '已收藏', wordSeen: '词汇练习',
  next: '下一题', back: '返回', previous: '上一题', bookmark: '收藏', unbookmark: '取消收藏',
  reveal: '查看参考答案', right: '回答正确', mistake: '再看一下解析', explanation: '解析',
  selfCorrect: '掌握了', selfWrong: '还需练习', empty: '当前范围暂无题目。试试其他等级或学习语言。',
  emptyWords: '这个语言与等级暂时没有词卡。', remember: '记得', forget: '忘了', revealWord: '查看释义',
  context: '单词＋语境', word: '纯单词', wordMode: '背词模式',
  guest: '游客 · 记录保存在本机', loading: '正在同步…', synced: '已连接网站账号', failed: '未确认同步，请刷新检查',
  refresh: '刷新云端记录', signIn: '登录', signOut: '退出登录', email: '网站账号邮箱', password: '密码',
  accountIntro: '使用 pikku.qzz.io 的同一邮箱账号，继续学习进度、收藏和背词统计。',
  accountNote: '游客记录仅在本机保存，不会自动并入登录账号。显示语言独立保存在本机。',
  register: '注册或找回密码', website: '复制网站地址', copied: '已复制，请在浏览器打开',
  websiteHelp: '请在网站注册、验证邮箱或找回密码，然后返回小程序登录。',
  syncError: '请求未完成，可能尚未同步。请检查网络并刷新云端记录。',
  syncUnknown: '结果尚未确认，请刷新云端记录核对。本次不会自动重传。',
  updated: '已刷新', required: '请填写邮箱和密码', source: '来源', draft: '内容草稿', reviewed: '已复核', published: '已发布', archived: '已归档',
  noResources: '本语言的资源目录仍在整理。', resourceNote: '书目信息与学习参考；不提供教材全文。',
  dictionary: '词典', textbooks: '教材目录', resourceCopy: '复制链接',
  seedNote: '该语言目前为四档种子练习，完整课程仍在建设。',
  privacy: '账号与数据', privacyText: '登录时，邮箱及密码经 HTTPS 发送至 Pikku 现有身份服务。学习记录、收藏及词汇统计保存到网站同一账号；登录凭据保存在本机。退出会清除本机登录凭据。游客学习记录保存在本机。',
  contentNote: '切换显示语言会改变界面；已有题干、释义和资料保留原文。',
  choose: '选择学习范围', search: '搜索题目', results: '题目', open: '打开', browse: '浏览题库',
  categories: { all: '全部题型', vocabulary: '词汇', morphology: '词形', syntax: '句法', sentencePattern: '句型', classics: '原典', translation: '翻译' },
};
const en = {
  home: 'Today', practice: 'Practice', words: 'Words', account: 'Account', resources: 'Resources',
  title: 'A little language, every day.', subtitle: 'One Pikku account. Keep your learning close.',
  learning: 'Learning language', display: 'Display language', start: 'Start practice', all: 'All questions', wrong: 'Review mistakes', saved: 'Bookmarks',
  answered: 'Completed', correct: 'Correct', bookmarked: 'Saved', wordSeen: 'Word reviews',
  next: 'Next question', back: 'Back', previous: 'Previous', bookmark: 'Save', unbookmark: 'Unsave',
  reveal: 'Show model answer', right: 'Correct', mistake: 'Review the explanation', explanation: 'Explanation',
  selfCorrect: 'Understood', selfWrong: 'Needs practice', empty: 'No questions in this selection. Try another level or language.',
  emptyWords: 'No word cards for this language and level yet.', remember: 'Remembered', forget: 'Forgot', revealWord: 'Show meaning',
  context: 'Word + context', word: 'Word only', wordMode: 'Word mode',
  guest: 'Guest · saved on this device', loading: 'Syncing…', synced: 'Connected to your web account', failed: 'Sync unconfirmed — refresh to check',
  refresh: 'Refresh cloud records', signIn: 'Sign in', signOut: 'Sign out', email: 'Website account email', password: 'Password',
  accountIntro: 'Use the same email account as pikku.qzz.io for your progress, bookmarks and vocabulary statistics.',
  accountNote: 'Guest records stay on this device and are not automatically merged into an account. Display language stays on this device.',
  register: 'Register or reset password', website: 'Copy website address', copied: 'Copied — open in your browser',
  websiteHelp: 'Register, verify your email or reset your password on the website, then return here to sign in.',
  syncError: 'Request did not complete. Check your connection and refresh cloud records.',
  syncUnknown: 'Result unconfirmed. Refresh cloud records to check; this attempt will not be sent again automatically.',
  updated: 'Refreshed', required: 'Enter your email and password', source: 'Source', draft: 'Draft content', reviewed: 'Reviewed', published: 'Published', archived: 'Archived',
  noResources: 'The resource directory for this language is being prepared.', resourceNote: 'Bibliographic information and study references; no textbook downloads.',
  dictionary: 'Dictionaries', textbooks: 'Textbook directory', resourceCopy: 'Copy link',
  seedNote: 'This language currently has seed exercises at four levels. The full course is still being developed.',
  privacy: 'Account and data', privacyText: 'Your email and password are sent over HTTPS to Pikku’s existing identity service. Progress, bookmarks and word statistics are stored in the same website account. Sign-in credentials are stored on this device and removed on sign-out. Guest records stay on this device.',
  contentNote: 'The display setting changes the interface. Existing questions, meanings and resources keep their original text.',
  choose: 'Choose your learning range', search: 'Search questions', results: 'questions', open: 'Open', browse: 'Browse questions',
  categories: { all: 'All types', vocabulary: 'Vocabulary', morphology: 'Morphology', syntax: 'Syntax', sentencePattern: 'Patterns', classics: 'Classics', translation: 'Translation' },
};
function levelCards(locale) {
  const labels = locale === 'en'
    ? [['C', '', 'C', 'ore'], ['F', '', 'F', 'unctional'], ['G', '', 'G', 'enerative'], ['M', '', 'M', 'astery']]
    : [['C', '', '初', '级'], ['F', '', '凡', '级'], ['G', '', '高', '级'], ['M', '准', '母', '语级']];
  return labels.map(([id, prefix, emphasis, suffix]) => ({ id, prefix, emphasis, suffix, icon: '/assets/level-' + id.toLowerCase() + '.png' }));
}
module.exports = { copies: { 'zh-CN': zh, en }, levelCards };
