import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import sharp from "sharp";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedNotice = "// Generated by scripts/build-wechat.mjs from the website sources. Do not edit.\n";

// TypeScript exists only in this build step; the mini program receives plain CommonJS.
export function createSourceLoader(root = projectRoot) {
  const cache = new Map();
  function load(relativePath) {
    const filename = path.resolve(root, relativePath);
    if (cache.has(filename)) return cache.get(filename).exports;
    const module = { exports: {} };
    cache.set(filename, module);
    const source = fs.readFileSync(filename, "utf8");
    const compiled = ts.transpileModule(source, {
      fileName: filename,
      compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
    }).outputText;
    const localRequire = (specifier) => {
      if (!specifier.startsWith(".")) throw new Error(`Unexpected data dependency: ${specifier}`);
      const resolved = path.resolve(path.dirname(filename), specifier);
      return load(path.extname(resolved) ? resolved : `${resolved}.ts`);
    };
    vm.runInThisContext(`(function (exports, require, module) {\n${compiled}\n})`, { filename })(module.exports, localRequire, module);
    return module.exports;
  }
  return load;
}

function parseSource(relativePath, root = projectRoot) {
  const filename = path.join(root, relativePath);
  return ts.createSourceFile(filename, fs.readFileSync(filename, "utf8"), ts.ScriptTarget.Latest, true,
    filename.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
}

function findVariable(source, name) {
  let result;
  function visit(node) {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.name.text === name) result = node;
    ts.forEachChild(node, visit);
  }
  visit(source);
  if (!result) throw new Error(`Missing source variable: ${name}`);
  return result;
}

export function loadProjectData(root = projectRoot) {
  const load = createSourceLoader(root);
  const page = parseSource("app/page.tsx", root);
  const imports = new Map();
  for (const node of page.statements) {
    if (!ts.isImportDeclaration(node) || !node.importClause?.namedBindings || !ts.isNamedImports(node.importClause.namedBindings)) continue;
    for (const binding of node.importClause.namedBindings.elements) {
      imports.set(binding.name.text, { path: node.moduleSpecifier.text, name: (binding.propertyName ?? binding.name).text });
    }
  }
  const questionList = findVariable(page, "staticQuestions").initializer;
  if (!ts.isArrayLiteralExpression(questionList)) throw new Error("Website staticQuestions is no longer an array.");
  const questions = questionList.elements.flatMap((element) => {
    if (!ts.isSpreadElement(element) || !ts.isIdentifier(element.expression)) throw new Error("Review changed website question composition before packaging.");
    const binding = imports.get(element.expression.text);
    if (!binding?.path.startsWith("@/data/")) throw new Error("Unexpected website question module.");
    return load(`${binding.path.slice(2)}.ts`)[binding.name];
  });
  const languages = load("data/languages.ts");
  const resources = load("data/resources.ts");
  return {
    questions,
    vocabularyCards: load("data/vocabulary.ts").vocabularyCards,
    languageConfigs: languages.languageConfigs,
    languageOrder: languages.languageOrder,
    learningLanguages: load("app/i18n.ts").learningLanguages,
    textbookCatalog: resources.textbookCatalog,
    dictionarySources: resources.dictionarySources,
  };
}

function sourceDeclarations(relativePath, names, root) {
  const source = parseSource(relativePath, root);
  return names.map((name) => {
    const statement = source.statements.find((node) =>
      (ts.isFunctionDeclaration(node) && node.name?.text === name) ||
      (ts.isVariableStatement(node) && node.declarationList.declarations.some((declaration) => ts.isIdentifier(declaration.name) && declaration.name.text === name)));
    if (!statement) throw new Error(`Missing shared declaration ${relativePath}:${name}`);
    return statement.getText(source);
  }).join("\n\n");
}

export function buildSharedSource(root = projectRoot) {
  const page = parseSource("app/page.tsx", root);
  const bankInitializer = findVariable(page, "questionBank").initializer;
  const callback = ts.isCallExpression(bankInitializer) ? bankInitializer.arguments[0] : undefined;
  if (!callback || !ts.isArrowFunction(callback) || !ts.isBlock(callback.body)) throw new Error("Review changed website question override logic before packaging.");
  const source = [
    'const { learningLanguages } = require("./bank.js");',
    sourceDeclarations("data/questions.ts", ["pikkuLevels", "legacyPikkuLevels", "normalizePikkuLevel", "matchesLevel"], root),
    sourceDeclarations("data/vocabulary.ts", ["cumulativeVocabularyLevels", "vocabularyKey", "vocabularyLevelsFor", "vocabularyMatchesLevel", "adaptiveVocabularyWeight", "chooseNextVocabularyCard"], root),
    sourceDeclarations("lib/shuffle.ts", ["shuffle"], root),
    sourceDeclarations("app/i18n.ts", ["availableLearningLanguages", "normalizeLearningLanguage", "getLearningLanguage"], root),
    // Preserve the website's deletion, replacement, order, and review-status behavior.
    `export function mergeQuestionOverrides(staticQuestions, overrides = []) ${callback.body.getText(page)}`,
  ].join("\n\n");
  return generatedNotice + ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, removeComments: true },
  }).outputText;
}

function directoryBytes(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).reduce((total, entry) => {
    const filename = path.join(directory, entry.name);
    return total + (entry.isDirectory() ? directoryBytes(filename) : fs.statSync(filename).size);
  }, 0);
}

export async function buildWechat({ root = projectRoot, outputDir = path.join(root, "wechat/miniprogram") } = {}) {
  const data = loadProjectData(root);
  fs.mkdirSync(path.join(outputDir, "data"), { recursive: true });
  fs.mkdirSync(path.join(outputDir, "assets"), { recursive: true });
  fs.writeFileSync(path.join(outputDir, "data/bank.js"), `${generatedNotice}module.exports = ${JSON.stringify(data)};\n`);
  fs.writeFileSync(path.join(outputDir, "data/shared.js"), buildSharedSource(root));
  fs.copyFileSync(path.join(root, "public/pkuni-latinex-logo-final.png"), path.join(outputDir, "assets/logo.png"));
  for (const level of ["c", "f", "g", "m"]) {
    await sharp(path.join(root, `public/level-icons/${level}.svg`)).resize(192, 192).png().toFile(path.join(outputDir, `assets/level-${level}.png`));
  }
  const packageBytes = directoryBytes(outputDir);
  if (packageBytes >= 2 * 1024 * 1024) throw new Error(`Mini program main package exceeds 2 MiB: ${packageBytes} bytes.`);
  return {
    questions: data.questions.length,
    vocabularyCards: data.vocabularyCards.length,
    languages: data.languageOrder.length,
    questionCounts: Object.fromEntries(data.languageOrder.map((language) => [language, data.questions.filter((question) => (question.language ?? "la") === language).length])),
    packageBytes,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log(JSON.stringify(await buildWechat(), null, 2));
}
