import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import sharp from "sharp";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedNotice = "// Generated by scripts/build-wechat.mjs from the website sources. Do not edit.\n";

// TypeScript exists only in this build step; the mini program receives plain CommonJS.
export function createSourceLoader(root = projectRoot) {
  const cache = new Map();
  function load(relativePath) {
    const filename = path.resolve(root, relativePath);
    if (cache.has(filename)) return cache.get(filename).exports;
    const module = { exports: {} };
    cache.set(filename, module);
    const source = fs.readFileSync(filename, "utf8");
    if (filename.endsWith(".json")) { module.exports = JSON.parse(source); return module.exports; }
    const compiled = ts.transpileModule(source, {
      fileName: filename,
      compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true },
    }).outputText;
    const localRequire = (specifier) => {
      if (!specifier.startsWith(".")) throw new Error(`Unexpected data dependency: ${specifier}`);
      const resolved = path.resolve(path.dirname(filename), specifier);
      return load(path.extname(resolved) ? resolved : `${resolved}.ts`);
    };
    vm.runInThisContext(`(function (exports, require, module) {\n${compiled}\n})`, { filename })(module.exports, localRequire, module);
    return module.exports;
  }
  return load;
}

function parseSource(relativePath, root = projectRoot) {
  const filename = path.join(root, relativePath);
  return ts.createSourceFile(filename, fs.readFileSync(filename, "utf8"), ts.ScriptTarget.Latest, true,
    filename.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
}

function findVariable(source, name) {
  let result;
  function visit(node) {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.name.text === name) result = node;
    ts.forEachChild(node, visit);
  }
  visit(source);
  if (!result) throw new Error(`Missing source variable: ${name}`);
  return result;
}

export function loadProjectData(root = projectRoot) {
  const load = createSourceLoader(root);
  const page = parseSource("app/page.tsx", root);
  const imports = new Map();
  for (const node of page.statements) {
    if (!ts.isImportDeclaration(node) || !node.importClause?.namedBindings || !ts.isNamedImports(node.importClause.namedBindings)) continue;
    for (const binding of node.importClause.namedBindings.elements) {
      imports.set(binding.name.text, { path: node.moduleSpecifier.text, name: (binding.propertyName ?? binding.name).text });
    }
  }
  const questionList = findVariable(page, "staticQuestions").initializer;
  if (!ts.isArrayLiteralExpression(questionList)) throw new Error("Website staticQuestions is no longer an array.");
  const questions = questionList.elements.flatMap((element) => {
    if (!ts.isSpreadElement(element) || !ts.isIdentifier(element.expression)) throw new Error("Review changed website question composition before packaging.");
    const binding = imports.get(element.expression.text);
    if (!binding?.path.startsWith("@/data/")) throw new Error("Unexpected website question module.");
    return load(`${binding.path.slice(2)}.ts`)[binding.name];
  });
  const languages = load("data/languages.ts");
  const resources = load("data/resources.ts");
  return {
    questions,
    questionCollections: load("data/question-collections.ts").questionCollections,
    vocabularyCards: load("data/vocabulary.ts").vocabularyCards,
    languageConfigs: languages.languageConfigs,
    languageOrder: languages.languageOrder,
    learningLanguages: load("app/i18n.ts").learningLanguages,
    textbookCatalog: resources.textbookCatalog,
    dictionarySources: resources.dictionarySources,
  };
}

function sourceDeclarations(relativePath, names, root) {
  const source = parseSource(relativePath, root);
  return names.map((name) => {
    const statement = source.statements.find((node) =>
      (ts.isFunctionDeclaration(node) && node.name?.text === name) ||
      (ts.isVariableStatement(node) && node.declarationList.declarations.some((declaration) => ts.isIdentifier(declaration.name) && declaration.name.text === name)));
    if (!statement) throw new Error(`Missing shared declaration ${relativePath}:${name}`);
    return statement.getText(source);
  }).join("\n\n");
}

export function buildSharedSource(root = projectRoot) {
  const page = parseSource("app/page.tsx", root);
  const bankInitializer = findVariable(page, "questionBank").initializer;
  const callback = ts.isCallExpression(bankInitializer) ? bankInitializer.arguments[0] : undefined;
  if (!callback || !ts.isArrowFunction(callback) || !ts.isBlock(callback.body)) throw new Error("Review changed website question override logic before packaging.");
  const source = [
    'const { learningLanguages } = require("./bank.js");',
    sourceDeclarations("data/questions.ts", ["pikkuLevels", "legacyPikkuLevels", "normalizePikkuLevel", "matchesLevel", "questionOptionOrder"], root),
    sourceDeclarations("data/vocabulary.ts", ["cumulativeVocabularyLevels", "vocabularyKey", "vocabularyLevelsFor", "vocabularyMatchesLevel", "adaptiveVocabularyWeight", "chooseNextVocabularyCard", "vocabularyInCollection", "publicDictionaryReferences"], root),
    sourceDeclarations("data/question-collections.ts", ["questionInCollection", "questionForCollection", "collectionOrder"], root),
    sourceDeclarations("lib/shuffle.ts", ["shuffle"], root),
    sourceDeclarations("app/i18n.ts", ["availableLearningLanguages", "normalizeLearningLanguage", "getLearningLanguage"], root),
    // Preserve the website's deletion, replacement, order, and review-status behavior.
    `export function mergeQuestionOverrides(staticQuestions, overrides = []) ${callback.body.getText(page)}`,
  ].join("\n\n");
  return generatedNotice + ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, removeComments: true },
  }).outputText;
}

// Generate the same model and validation/sync contract; no mini-program model fork.
export function buildVocabularySource(name, root = projectRoot) {
  if (!["vocabulary-model", "vocabulary-review-sync"].includes(name)) throw new Error("Unexpected shared module.");
  let source = fs.readFileSync(path.join(root, `lib/${name}.ts`), "utf8");
  // Array.at is newer than the mini-program ES2019 runtime. Keep its one use equivalent.
  source = source.replace("rows.at(-1)", "rows[rows.length - 1]")
    .replace('"./vocabulary-model.ts"', '"./vocabulary-model.js"');
  return generatedNotice + ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, removeComments: true },
  }).outputText;
}

export function serializeBank(data) {
  const counts = new Map();
  function count(value) {
    if (typeof value === "string" && value.length >= 40) counts.set(value, (counts.get(value) ?? 0) + 1);
    else if (Array.isArray(value)) value.forEach(count);
    else if (value && typeof value === "object") Object.values(value).forEach(count);
  }
  count(data);
  const strings = [...counts].filter(([, count]) => count > 1).map(([value]) => value);
  const indices = new Map(strings.map((value, index) => [value, index]));
  function literal(value) {
    if (typeof value === "string" && indices.has(value)) return `s[${indices.get(value)}]`;
    if (Array.isArray(value)) return `[${value.map(literal).join(",")}]`;
    if (value && typeof value === "object") return `{${Object.entries(value).filter(([, v]) => v !== undefined).map(([k, v]) => `${JSON.stringify(k)}:${literal(v)}`).join(",")}}`;
    return JSON.stringify(value);
  }
  function records(items) {
    const keys = [...new Set(items.flatMap(item => Object.keys(item)))];
    const rows = items.map(item => {
      const values = keys.map(key => item[key] === undefined ? "" : literal(item[key]));
      while (values.length && !values[values.length - 1]) values.pop();
      return `[${values.join(",")}]`;
    });
    return `rows(${JSON.stringify(keys)},[${rows.join(",")}])`;
  }
  const body = Object.entries(data).map(([key, value]) => `${JSON.stringify(key)}:${["questions", "vocabularyCards"].includes(key) ? records(value) : literal(value)}`).join(",");
  return `${generatedNotice}const s = ${JSON.stringify(strings)};\nconst rows = (keys, values) => values.map(row => Object.fromEntries(Object.keys(row).map(index => [keys[index], row[index]])));\nmodule.exports = {${body}};\n`;
}

function directoryBytes(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).reduce((total, entry) => {
    const filename = path.join(directory, entry.name);
    return total + (entry.isDirectory() ? directoryBytes(filename) : fs.statSync(filename).size);
  }, 0);
}

export async function buildWechat({ root = projectRoot, outputDir = path.join(root, "wechat/miniprogram") } = {}) {
  const data = loadProjectData(root);
  fs.mkdirSync(path.join(outputDir, "data"), { recursive: true });
  fs.mkdirSync(path.join(outputDir, "assets"), { recursive: true });
  fs.writeFileSync(path.join(outputDir, "data/bank.js"), serializeBank(data));
  fs.writeFileSync(path.join(outputDir, "data/shared.js"), buildSharedSource(root));
  for (const name of ["vocabulary-model", "vocabulary-review-sync"]) {
    fs.writeFileSync(path.join(outputDir, `data/${name}.js`), buildVocabularySource(name, root));
  }
  const support = path.join(root, "wechat/static/support-author.png");
  if (fs.existsSync(support)) fs.copyFileSync(support, path.join(outputDir, "assets/support-author.png"));
  fs.copyFileSync(path.join(root, "public/pkuni-latinex-logo-final.png"), path.join(outputDir, "assets/logo.png"));
  for (const level of ["c", "f", "g", "m"]) {
    await sharp(path.join(root, `public/level-icons/${level}.svg`)).resize(192, 192).png().toFile(path.join(outputDir, `assets/level-${level}.png`));
  }
  const packageBytes = directoryBytes(outputDir);
  if (packageBytes >= 2 * 1024 * 1024) throw new Error(`Mini program main package exceeds 2 MiB: ${packageBytes} bytes.`);
  return {
    questions: data.questions.length,
    vocabularyCards: data.vocabularyCards.length,
    languages: data.languageOrder.length,
    questionCounts: Object.fromEntries(data.languageOrder.map((language) => [language, data.questions.filter((question) => (question.language ?? "la") === language).length])),
    packageBytes,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log(JSON.stringify(await buildWechat(), null, 2));
}
